### PR TITLE
Enable hot reload feature

### LINKED ISSUE #47: Enable hot reload feature
Let's enable hot reloading feature to improve develop process

### PR DESCRIPTION
**Pull request by kamontia**
Close #47

### CODE REVIEW

**Comment by kamontia** [comment]
@chaspy  Please review and merge.

You can confirm the changes by following way.

```
$ make build && make
```
Open browser and log in to view React view. You can check hot reload when some files are modified.

**Comment by chaspy** [comment]
😢 

```
Webpacker::Manifest::MissingEntryError in Todos#index
Showing /myapp/app/views/todos/index.html.erb where line #62 raised:

Webpacker can't find hello_react.js in /myapp/public/packs/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
2. webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your webpack configuration is not creating a manifest.
Your manifest contains:
{
```

**Comment by kamontia** [comment]
@chaspy I added new command in Makefile.

Please execute as below
```
$ make ts-build && make build && make
```

**Comment by chaspy** [comment]
Why do you need chown?

**Comment by kamontia** [comment]
> Why do you need chown?
To operate files by host user permission.
Resolved by #53

**Pull request merged**
